### ISSUE TITLE
Filter settings default to "skipfilteroptions" on.

### ISSUE THREAD

**Issue by discordier** [MetaModels/core#1089]
## Checklist before I submit this issue report

I confirm that:
- [X] I have tested this with the latest version available
- [X] I have read documentation @ http://metamodels.readthedocs.org/en/ or http://metamodels.readthedocs.org/de/
- [X] I have checked the Contao community forums for references https://community.contao.org/
- [X] I have checked existing issues for duplicates and found none @ https://github.com/MetaModels/core/issues?q=is%3Aissue

## My environment is:

(Please fill in the actual values from your environment)

| Key                                 | Value    | Comments                         |
| ----------------------------------- | ---------| ---------------------------------|
| PHP version:                        | all         |                                  |
| Contao version:                     | all         |                                  |
| MetaModels version:                 | all         |                                  |
| Installation via composer:          | does not matter |                                  |
| Installed MetaModels packages:      | all         |                                  |
| DCG version:                        | not related to dcg         |                                  |

## Issue description

(Describe the problem you are having)

## Steps to reproduce

1. Create a filter configuration
2. Use any filter in there which does NOT intend to honor "skipfilteroptions" (like "OR" and "AND")
 
## Describe the behaviour of the application

The flag "skipfilteroptions" will always be on and derived filters will therefore always skip options.
See [src/MetaModels/Filter/Setting/Collection.php](https://github.com/MetaModels/core/blob/126686a83b067ae410ac5b7a8834cb265e2bf99d/src/MetaModels/Filter/Setting/Collection.php#L202)

## Describe the expected behaviour of the application

Sometimes I definately do NOT want this to happen.

## Proposed solutions.

We have now two possibilities:
1. Allow to select the checkbox for all filters (needs configuration change in the filters repositories in the metapalette configuration).
2. Provide a way for filter settings to tell the `MetaModels\Filter\Collection` that they are not intended to be used with the `skipfilteroptions` flag.

Currently I tend to solution 1. as it is easier to implement and more explicit.

@MetaModels/team, @richardhj what do you think?

**Comment by richardhj** [comment]
As a side note:
The "skipfilteroptions" flag will always be on because, when not disabled in the input mask explicitly, of https://github.com/MetaModels/core/blob/46370fb8df9e751c9f6d0b2d10399fdf161fadf4/contao/dca/tl_metamodel_filtersetting.php#L499

When decided for possibility 1:
* We can use the `BuildDataDefinitionEvent` to define the "skipfilteroptions" flag as `false` for filters that does not intend to honor "skipfilteroptions" (set `$GLOBALS['TL_DCA']['tl_metamodel_filtersetting']['fields']['skipfilteroptions']['default']` to `false`)
* We might not have to update the filter's repositories but update the core metapalette at https://github.com/MetaModels/core/blob/46370fb8df9e751c9f6d0b2d10399fdf161fadf4/contao/dca/tl_metamodel_filtersetting.php#L226

But at at the end I'm not happy with messing up the palettes. Are they filter settings that definitely do not want to honor the `skipfilteroptions` flag? Then the checkbox does not make any sense and possibility 2 would be the correct one; although I like the explicit way of the checkbox.

**Comment by zonky2** [comment]
Telefonat [09.03.2018] mit xtra: wir setzen den Wert per default auf false und nur die Filter, die was mit dem Wert anfangen können, können den Wert per Checkbox aktivieren.

**Comment by discordier** [comment]
closing in favor of #1224
